### ISSUE TITLE
Can release note's commits only get from master branch?

### ISSUE THREAD

**Issue by marsz** [hahow/probot-conventional-release#3]
When push master directly with new commits, there are some commits which is not included in master also been published on release note.

The error scenario is: 
```
Given v1.0.0 has commit A & B both in develop and master branch
  And hotfix commit C merged into master, feature commit D merged into develop
 When push develop, then push master
 Then commit C, D both show on release note (should be only commit C)
```

Thanks for helping :)

**Comment by amowu** [comment]
Hi @marsz 請原諒我用中文回覆，請問你是直接安裝我們的 [App](https://github.com/apps/conventional-release-bot) 還是自己另外 fork 一份安裝的呢？謝謝。😀

**Comment by marsz** [comment]
Hi @amowu 
我是直接裝 app 的。問題應該是發生在直接 push master 時，也會把非 master 內的 conventional commit 也寫進 release note 裡。
感謝 :)

**Comment by amowu** [comment]
新版本的觸發條件已從 push master 改為 open pull_request(merge master) 囉
