### ISSUE TITLE
BREAKING CHANGE 無效

### ISSUE THREAD

**Issue by marsz** [hahow/probot-conventional-release#5]
我在 commit message 中輸入如下:

```
BREAKING CHANGE: xxxxxx
```

merge 進 develop 後， tag 沒有從 0.xx.yy 到 1.0.0

:(

**Comment by amowu** [comment]
Hi @marsz ，請問 `BREAKING CHANGE` 是寫在 commit message 的 body 或 footer 嗎？例如：

```
feat: xxx

BREAKING CHANGE: xxx
```

Or

```
fix: xxx

xxx

BREAKING CHANGE: xxx
```

**Comment by marsz** [comment]
可以了，感謝 :D
